"""Adding missing enums and stuff 3

Revision ID: 43413468d127
Revises: 9dc9da25685c
Create Date: 2025-10-25 20:00:30.677836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43413468d127'
down_revision = '9dc9da25685c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
