"""Adding missing enums and stuff 6

Revision ID: 5e9dcd162523
Revises: 742189854a8e
Create Date: 2025-10-26 07:58:12.422688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9dcd162523'
down_revision = '742189854a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
