"""Adding missing enums and stuff 5

Revision ID: 742189854a8e
Revises: 4606f467f7ec
Create Date: 2025-10-25 21:06:31.629717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742189854a8e'
down_revision = '4606f467f7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
