"""Adding missing enums and stuff 2

Revision ID: 9dc9da25685c
Revises: 6d5baf12bf8e
Create Date: 2025-10-25 19:57:07.452873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc9da25685c'
down_revision = '6d5baf12bf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=150), nullable=False))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_name')
        batch_op.drop_column('reporter_name')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
